"""Add phase 3 models

Revision ID: 34171315a808
Revises: 6edf8f62fb85
Create Date: 2026-09-14 18:42:35.937354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34171315a808'
down_revision: Union[str, Sequence[str], None] = '6edf8f62fb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('modality', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('effort_score', sa.Float(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('score_earned', sa.Integer(), nullable=False),
    sa.Column('proof_image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_records_date'), 'activity_records', ['date'], unique=False)
    op.create_index(op.f('ix_activity_records_group_id'), 'activity_records', ['group_id'], unique=False)
    op.create_index(op.f('ix_activity_records_user_id'), 'activity_records', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('effort_total', sa.Float(), nullable=False),
    sa.Column('consistency_total', sa.Float(), nullable=False),
    sa.Column('challenges_total', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    op.create_table('competitive_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('effort_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('challenge_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'period_start', 'period_end', name='uq_member_period')
    )
    op.create_index(op.f('ix_competitive_scores_membership_id'), 'competitive_scores', ['membership_id'], unique=False)
    op.create_index(op.f('ix_competitive_scores_period_end'), 'competitive_scores', ['period_end'], unique=False)
    op.create_index(op.f('ix_competitive_scores_period_start'), 'competitive_scores', ['period_start'], unique=False)
    op.add_column('groups', sa.Column('group_type', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_type')
    op.drop_index(op.f('ix_competitive_scores_period_start'), table_name='competitive_scores')
    op.drop_index(op.f('ix_competitive_scores_period_end'), table_name='competitive_scores')
    op.drop_index(op.f('ix_competitive_scores_membership_id'), table_name='competitive_scores')
    op.drop_table('competitive_scores')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_activity_records_user_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_group_id'), table_name='activity_records')
    op.drop_index(op.f('ix_activity_records_date'), table_name='activity_records')
    op.drop_table('activity_records')
    # ### end Alembic commands ###
