"""Baseline

Revision ID: c0e5b05412b6
Revises: 
Create Date: 2026-09-14 17:50:24.134275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e5b05412b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_invite_code'), 'groups', ['invite_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('avatar', sa.String(length=8), nullable=False),
    sa.Column('photo', sa.Text(), nullable=True),
    sa.Column('objetivo', sa.String(length=200), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('nivel_atividade', sa.String(length=20), nullable=True),
    sa.Column('objetivo_tipo', sa.String(length=10), nullable=True),
    sa.Column('meta_kcal', sa.Integer(), nullable=True),
    sa.Column('meta_proteina_g', sa.Integer(), nullable=True),
    sa.Column('meta_carbo_g', sa.Integer(), nullable=True),
    sa.Column('meta_gordura_g', sa.Integer(), nullable=True),
    sa.Column('meta_agua_l', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_memberships_group_id'), 'memberships', ['group_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_token_hash'), 'password_resets', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_resets_user_id'), 'password_resets', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('water_goal_l', sa.Float(), nullable=False),
    sa.Column('steps_goal', sa.Integer(), nullable=False),
    sa.Column('protein_goal_g', sa.Integer(), nullable=False),
    sa.Column('calories_goal', sa.Integer(), nullable=False),
    sa.Column('sleep_goal_h', sa.Float(), nullable=False),
    sa.Column('rest_days', sa.JSON(), nullable=False),
    sa.Column('spiritual_enabled', sa.Boolean(), nullable=False),
    sa.Column('surprise_frequency', sa.Float(), nullable=False),
    sa.Column('fixed_habits', sa.JSON(), nullable=False),
    sa.Column('challenge_pool', sa.JSON(), nullable=False),
    sa.Column('challenge_pool_updated', sa.DateTime(), nullable=True),
    sa.Column('custom_challenges', sa.JSON(), nullable=False),
    sa.Column('disabled_areas', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_group_id'), 'settings', ['group_id'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('ref', sa.String(length=40), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_day'), 'activities', ['day'], unique=False)
    op.create_index(op.f('ix_activities_group_id'), 'activities', ['group_id'], unique=False)
    op.create_table('day_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('habits_done', sa.JSON(), nullable=False),
    sa.Column('habit_proofs', sa.JSON(), nullable=False),
    sa.Column('challenge_proofs', sa.JSON(), nullable=False),
    sa.Column('challenge_rerolls', sa.JSON(), nullable=False),
    sa.Column('challenge_together', sa.JSON(), nullable=False),
    sa.Column('moods', sa.JSON(), nullable=False),
    sa.Column('mood_note', sa.Text(), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'date', name='uq_membership_date')
    )
    op.create_index(op.f('ix_day_entries_date'), 'day_entries', ['date'], unique=False)
    op.create_index(op.f('ix_day_entries_membership_id'), 'day_entries', ['membership_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_group_id'), 'goals', ['group_id'], unique=False)
    op.create_table('joint_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_joint_activities_created_at'), 'joint_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_joint_activities_date'), 'joint_activities', ['date'], unique=False)
    op.create_index(op.f('ix_joint_activities_group_id'), 'joint_activities', ['group_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_created_at'), 'meals', ['created_at'], unique=False)
    op.create_index(op.f('ix_meals_date'), 'meals', ['date'], unique=False)
    op.create_index(op.f('ix_meals_group_id'), 'meals', ['group_id'], unique=False)
    op.create_index(op.f('ix_meals_membership_id'), 'meals', ['membership_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_group_id'), 'messages', ['group_id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('icon', sa.String(length=24), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_group_id'), 'scheduled_tasks', ['group_id'], unique=False)
    op.create_table('activity_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'membership_id', name='uq_activity_member')
    )
    op.create_index(op.f('ix_activity_reactions_activity_id'), 'activity_reactions', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_reactions_membership_id'), 'activity_reactions', ['membership_id'], unique=False)
    op.create_table('goal_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'membership_id', 'date', name='uq_goal_member_date')
    )
    op.create_index(op.f('ix_goal_checkins_date'), 'goal_checkins', ['date'], unique=False)
    op.create_index(op.f('ix_goal_checkins_goal_id'), 'goal_checkins', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_checkins_membership_id'), 'goal_checkins', ['membership_id'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'membership_id', 'date', name='uq_task_member_date')
    )
    op.create_index(op.f('ix_task_completions_date'), 'task_completions', ['date'], unique=False)
    op.create_index(op.f('ix_task_completions_membership_id'), 'task_completions', ['membership_id'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_membership_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_date'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_goal_checkins_membership_id'), table_name='goal_checkins')
    op.drop_index(op.f('ix_goal_checkins_goal_id'), table_name='goal_checkins')
    op.drop_index(op.f('ix_goal_checkins_date'), table_name='goal_checkins')
    op.drop_table('goal_checkins')
    op.drop_index(op.f('ix_activity_reactions_membership_id'), table_name='activity_reactions')
    op.drop_index(op.f('ix_activity_reactions_activity_id'), table_name='activity_reactions')
    op.drop_table('activity_reactions')
    op.drop_index(op.f('ix_scheduled_tasks_group_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_messages_group_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_meals_membership_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_group_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_date'), table_name='meals')
    op.drop_index(op.f('ix_meals_created_at'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_joint_activities_group_id'), table_name='joint_activities')
    op.drop_index(op.f('ix_joint_activities_date'), table_name='joint_activities')
    op.drop_index(op.f('ix_joint_activities_created_at'), table_name='joint_activities')
    op.drop_table('joint_activities')
    op.drop_index(op.f('ix_goals_group_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_day_entries_membership_id'), table_name='day_entries')
    op.drop_index(op.f('ix_day_entries_date'), table_name='day_entries')
    op.drop_table('day_entries')
    op.drop_index(op.f('ix_activities_group_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_day'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_settings_group_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_password_resets_user_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_token_hash'), table_name='password_resets')
    op.drop_table('password_resets')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_group_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_groups_invite_code'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
